### PR TITLE
Bump slab to v0.4.7

### LINKED ISSUE #131: Old slab version in dependencies breaks build
async-executor has a dependency on a really old version of slab.

`slab = "0.4.4"`

The problem is that this version no longer compiles with any remotely recent version of Rust:

```
error[E0015]: cannot call non-const fn `Slab::<Waker>::new` in constant functions
   --> /home/robin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.13.1/src/lib.rs:693:32
    |
693 |             active: Mutex::new(Slab::new()),
    |                                ^^^^^^^^^^^
    |
    = note: calls in constant functions are limited to constant functions, tuple structs and tuple variants
```

This was fixed back in 2022 and shipped with slab 0.4.7.

### PR DESCRIPTION
**Pull request by notgull**
Closes #131

### CODE REVIEW

**Review by taiki-e — APPROVED** [review]

**Comment by mrzv** [comment]
Can you please release a new version that includes this change?

**Comment by taiki-e** [comment]
Creating a new release is fine, but this is just a minimal version issue that can be fixed by just running `cargo update` without a new release.

**Comment by mrzv** [comment]
Sorry, I don't understand. What do I tell `cargo update` so it grabs a version of `async-executor` that includes this change?

**Comment by taiki-e** [comment]
This PR just raises the *minimal* version requirement for slab. Even without an async-executor containing this change, a `cargo update` on your part will increase the slab version and thus fix the problem.

**Comment by mrzv** [comment]
But it didn't. I ran into this problem precisely after running `cargo update` (from a 4-year-old code base).

**Comment by mrzv** [comment]
Sorry. I'm wrong, it popped up after `cargo upgrade`.

**Comment by taiki-e** [comment]
Since `cargo upgrade` brings direct dependencies up to the latest version and does nothing for indirect dependencies, so I think that running `cargo update` should bring the slab version up to date as well.

**Comment by mrzv** [comment]
Yeah, it's all fixed. I got confused between the two commands. Thanks for explaining, and sorry for the spam.

**Comment by taiki-e** [comment]
Published in 1.13.2.

**Pull request merged**
