### PR TITLE
v1.12.0

### PR DESCRIPTION
**Pull request by notgull**
- Add static executors, which are an optimization over executors that are kept
  around forever. (#112)

### CODE REVIEW

**Review by james7132 — APPROVED** [review]

**Comment by notgull** [comment]
@taiki-e Any chance you can review this? This is blocking performance improvements in Bevy.

(If you don't have time it's already been reviewed by other members so I'm fine publishing this.)

**Comment by taiki-e** [comment]
> Add static executors, which are an optimization over executors that are kept
around forever. (https://github.com/smol-rs/async-executor/pull/112)

Is it confirmed that the performance issue is not handled well by inlining?

When I received a similar request on crossbeam before, it could be handled almost well with inlining alone.
https://github.com/crossbeam-rs/crossbeam/issues/979#issuecomment-1528824012

**Comment by notgull** [comment]
Apparently the core issue was the locking of the `Mutex` used to abort the task when the `Executor` is dropped. When this `Mutex` isn't being locked Bevy has observed noticeable performance gains.

**Comment by notgull** [comment]
Ref: https://github.com/smol-rs/async-executor/pull/112#issuecomment-2059556711

**Review by taiki-e — APPROVED** [review]

**Pull request merged**
