### PR TITLE
add Executor::is_empty and LocalExecutor::is_empty

### LINKED ISSUE #13: Add something like LocalExecutor::block_on_all
What I would want to do is something like block_on, but which would wait on the passwed futures and all the ones that have been spawned on this executor.
While it doesnt' really make sense for Executor (as long as you keep one running), as it's work stealing across threads, dropping a LocalExecutor ofter the future passed to block_on has finished would end up losing all the spawned ones on the LocalExecutor, unless I'm missing something obvious

### PR DESCRIPTION
**Pull request by Keruspe**
Fixes #13

### CODE REVIEW

**Comment by Keruspe** [comment]
I'm not particularly bound to this implementation but it would be great to at least expose in some way what is_empty does

**Comment by stjepang** [comment]
What if we simply add `Executor::is_empty()` and `LocalExecutor::is_empty()`?

**Comment by Keruspe** [comment]
Would be fine by me

**Review by stjepang — APPROVED** [review]

**Comment by stjepang** [comment]
Published v1.4.0

**Pull request merged**
